[add] 搭建软件包基本框架
RT-Thread-packages/LiteOS-SDK pull request #1
Opened 2023-08-07 15:03 UTC by liYony

2023-08-07 17:00 UTC, mysterywolf commented on hwsecurec/SConscript
> +group = DefineGroup('hwsecurec', src, depend = ['PKG_LITEOS_SDK_HWSECUREC_EN'], CPPPATH = inc)
EN是啥意思？

2023-08-08 00:10 UTC, liYony commented
enable





------------------ 原始邮件 ------------------
发件人: Meco Man ***@***.***&gt;
发送时间: 2023年8月8日 01:00
收件人: RT-Thread-packages/LiteOS-SDK ***@***.***&gt;
抄送: liYangYang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [RT-Thread-packages/LiteOS-SDK] [add] 搭建软件包基本框架 (PR #1)





 
@mysterywolf commented on this pull request.
 
 
In hwsecurec/SConscript:
 &gt; @@ -0,0 +1,9 @@ +from building import * + +cwd = GetCurrentDir() + "/include" +src = Glob('src/*.c') +inc = [cwd] + +group = DefineGroup('hwsecurec', src, depend = ['PKG_LITEOS_SDK_HWSECUREC_EN'], CPPPATH = inc)  
EN是啥意思？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-08-08 00:50 UTC, mysterywolf requested changes
用这个名字

2023-08-08 00:50 UTC, mysterywolf commented on hwsecurec/SConscript
> +group = DefineGroup('hwsecurec', src, depend = ['PKG_LITEOS_SDK_HWSECUREC_EN'], CPPPATH = inc)
```suggestion
group = DefineGroup('hwsecurec', src, depend = ['PKG_LITEOS_SDK_USING_HWSECUREC'], CPPPATH = inc)
```

2023-08-08 13:26 UTC, mysterywolf approved these changes

2023-08-08 13:26 UTC, merged